language: node_js
node_js:
  - node
before_script:
  - npm install -g grunt-cli
script:
  - npm run-script check-html
  - npm run-script check-js
  - npm test
after_script:
  - npm run-script coveralls
  - npm run-script codeclimate
