sudo: false
language: node_js
node_js:
  - node
  - iojs
before_script:
  - npm install -g grunt-cli
  - ./conta_linhas.sh
script:
  - npm run lint
  - npm test
  - npm run docs
  - npm run build
after_script:
  - npm run coveralls
  - npm run codecov.io
