sudo: false
language: node_js
node_js:
  - node
before_script:
  - npm install -g grunt-cli
script:
  - npm run check-html
  - npm run check-js
  - npm test
  - npm run build
after_script:
  - npm run coveralls
